language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_success:
  - bash <(curl -s https://codecov.io/bash)
